import type { Account } from "@/features/accounts/domain/types";
import type { Category } from "@/features/categories/domain/types";
import type { Transaction } from "@/features/transactions/domain/types";

export const accountsFixture: Account[] = [
  {
    id: "account-cash",
    user_id: "user-1",
    name: "Cash Wallet",
    type: "cash",
    balance: 2500,
    color: null,
    icon: null,
    is_default: false,
    is_active: true,
    created_at: "2026-05-01T00:00:00.000Z",
    updated_at: "2026-05-01T00:00:00.000Z",
    deleted_at: null,
  },
  {
    id: "account-bank",
    user_id: "user-1",
    name: "SBI Savings",
    type: "bank",
    balance: 25000,
    color: null,
    icon: null,
    is_default: true,
    is_active: true,
    created_at: "2026-05-02T00:00:00.000Z",
    updated_at: "2026-05-02T00:00:00.000Z",
    deleted_at: null,
  },
];

export const categoriesFixture: Category[] = [
  {
    id: "category-food",
    user_id: null,
    name: "Food & Dining",
    icon: "FD",
    color: null,
    type: "expense",
    is_default: true,
    created_at: "2026-05-01T00:00:00.000Z",
    deleted_at: null,
  },
  {
    id: "category-transport",
    user_id: null,
    name: "Transportation",
    icon: "TR",
    color: null,
    type: "expense",
    is_default: true,
    created_at: "2026-05-01T00:00:00.000Z",
    deleted_at: null,
  },
  {
    id: "category-salary",
    user_id: null,
    name: "Salary",
    icon: "SA",
    color: null,
    type: "income",
    is_default: true,
    created_at: "2026-05-01T00:00:00.000Z",
    deleted_at: null,
  },
  {
    id: "category-misc",
    user_id: "user-1",
    name: "Miscellaneous",
    icon: "MI",
    color: null,
    type: "both",
    is_default: false,
    created_at: "2026-05-01T00:00:00.000Z",
    deleted_at: null,
  },
];

export const transactionsFixture: Transaction[] = [
  {
    id: "transaction-expense",
    user_id: "user-1",
    account_id: "account-bank",
    category_id: "category-food",
    type: "expense",
    amount: 450,
    note: "Dinner",
    merchant_name: "Swiggy",
    date: "2026-05-10",
    time: null,
    payment_method: null,
    created_at: "2026-05-10T18:00:00.000Z",
    updated_at: "2026-05-10T18:00:00.000Z",
    deleted_at: null,
    accounts: {
      id: "account-bank",
      name: "SBI Savings",
      type: "bank",
    },
    categories: {
      id: "category-food",
      name: "Food & Dining",
      icon: "FD",
      color: null,
      type: "expense",
    },
  },
  {
    id: "transaction-income",
    user_id: "user-1",
    account_id: "account-bank",
    category_id: "category-salary",
    type: "income",
    amount: 60000,
    note: "May salary",
    merchant_name: null,
    date: "2026-05-09",
    time: null,
    payment_method: null,
    created_at: "2026-05-09T09:00:00.000Z",
    updated_at: "2026-05-09T09:00:00.000Z",
    deleted_at: null,
    accounts: {
      id: "account-bank",
      name: "SBI Savings",
      type: "bank",
    },
    categories: {
      id: "category-salary",
      name: "Salary",
      icon: "SA",
      color: null,
      type: "income",
    },
  },
];
